---
title: "Booktitle"
subtitle: "A Fitting Subtitle (Or Not)"
author:
    - Maik Thalmann^[Georg-August-University Göttingen, maik.thalmann@gmail.com]
date: "Göttingen, `r format(Sys.time(), '%d %B, %Y')`"
publishers: "Georg-August-University Göttingen"
subject: "Linguistics"
titlehead: "Some Titlehead"
contact: https://mkthalmann.github.io/home/
fontsize: 11pt
output:
 pdf_document:
    toc: true
    pandoc_args: 
        - "--highlight=tango"
        - "--top-level-division=part"
    template: template.tex
    citation_package: biblatex
    keep_tex: true
    latex_engine: xelatex
    dev: cairo_pdf
documentclass: scrartcl
bibliography: ../bibliographyuni.bib
mainfont: XITS
sansfont: "Source Sans Pro"
monofont: "Hack"
mathfont: "Asana Math"
---

```{r import, echo=FALSE, warning=FALSE, message=FALSE}
# read chunk (does not run code)
library(knitr)
read_chunk('setup.R')
```

```{r setup, echo=FALSE, warning=FALSE, message=FALSE}
```

# Part

## A Section

```{r data, echo = TRUE}
d <- diamonds

d %>%
    head() %>%
    kable(booktabs = T, caption = "Data we will be working with.") %>%
    kable_styling(position = "center", latex_options = "hold_position")
```

## Another Section

In Figure \ref{tab:dlookrdiag}, we can see the amount and proportion of missing data; and I'm checking to see how references work. 

```{r dlookrdiag}
d %>%
    diagnose() %>%
    kable(booktabs = T, caption = "Missing values check.") %>%
    kable_styling(position = "center", latex_options = "hold_position")
```

```{r dlookrdesc}
d %>%
    group_by(cut) %>%
    describe(price) %>%
    select(-starts_with("p")) %>%
    kable(booktabs = T, caption = "Descriptive statistics for diamond price based on the diamond cut.") %>%
    kable_styling(position = "center", latex_options = "hold_position")
```

```{r report}
d %>%
    report_sample(group_by = "cut", select = c("price")) %>%
    as.data.frame() %>%
    kable(booktabs = T, caption = "Data overview.") %>%
    kable_styling(position = "center", latex_options= c("scale_down", "hold_position"))
```

### A Subsection

### Another Subsection

```{r mean-lines, fig.cap = "A sample plot."}
ggplot(d, aes(x = cut, y = price, color = price)) +
    stat_summary(fun.y = mean, geom = "line", mapping = aes(group = 1)) +
    stat_summary(fun.y = mean, geom = "point") +
    stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width = .25) +
    theme_maik() +
    scale_color_grey()
```

# Another Part

## Some Additional Section

@tarski1944semantic

@dayal2009variation

## All The Code I Used {.unlisted .unnumbered}

```{r get-labels, echo = FALSE}
labs = knitr::all_labels()
labs = setdiff(labs, c("import", "setup", "get-labels"))
```

```{r all-code, ref.label=labs, eval = FALSE, echo = TRUE}
```